experiment_name: demo_roco_whyxrayclip_chestxray
device: auto

dataset:
  name: roco
  params:
    zip_path: /content/drive/MyDrive/MAESTRIA-TESIS/datasets/ROCO/dataset_roco.zip
    split: validation
    n_rows: all
    images_subdir: all_data/validation/radiology/images
    caption_regex: "chest x-ray|lung"
    casefold: true
    columns:
      image_key: name
      caption_key: caption

model:
  name: whyxrayclip-vit-l-14
  params:
    # Puedes sobreescribir 'pretrained' o 'tokenizer' si clonas el modelo localmente.
    # pretrained: hf-hub:yyupenn/whyxrayclip
    # tokenizer: ViT-L-14
