experiment_name: demo_roco_whyxrayclip
device: auto

dataset:
  name: roco
  params:
    zip_path: data/dataset_roco.zip
    split: validation
    n_rows: all
    columns:
      image_key: name
      caption_key: caption
      images_subdir: all_data/validation/radiology/images

model:
  name: whyxrayclip
  params:
    model_name: hf-hub:yyupenn/whyxrayclip
    tokenizer_name: ViT-L-14
    # Para desarrollo rápido, descomenta la siguiente línea:
    # shap_call_kwargs: {"max_evals": 100}